### PR TITLE
Improve git.Tests.ps1

### PR DESCRIPTION
**Pull request by RyanSpr**
added version check to git.Tests.ps1

### CODE REVIEW

**Review by alex-yates-redgate — CHANGES_REQUESTED** [review]
Very nice PR.

In reviewing it, I spotted a copy paste mistake of my own. The Describe line on line 17 is a bit of copy pasta left over from when I originally copy pasted this file from one of the other test files. It should really say something more relevant to the tests.

Propose we split up the tests into logical "describe blocks". Perhaps we could do either of the following:

EITHER:
Describe "The following git repositories should exist in C:/git"{
  It "vm-ststua-checks" {...} # i.e. trimming down the title in the "It" block
  It "tdm-demos" {...}
  etc
}
Describe "The following repos should be up to date"{
  It "vm-ststua-checks" {...} 
  It "tdm-demos" {...}
  etc
}

Or:

Describe "Verifying vm-status-checks repository"{
  It "repo exists" {...}
  It "repo up to date" {...}
}
Describe "Verifying tdm-demos repository"{
  It "repo exists" {...}
  It "repo up to date" {...}
}

On balance, I prefer option 1, but what do you think?

Also, I bet it's possible to do something with for loops, so we can effectively just create a list of repo names at the top, and loop through them all, without needing to copy paste all over the place every time we either add a new repo, or a new test to run against all our repos, but we don't need to do that bit now.

**Comment by RyanSpr** [comment]
> Very nice PR.
> 
> In reviewing it, I spotted a copy paste mistake of my own. The Describe line on line 17 is a bit of copy pasta left over from when I originally copy pasted this file from one of the other test files. It should really say something more relevant to the tests.
> 
> Propose we split up the tests into logical "describe blocks". Perhaps we could do either of the following:
> 
> EITHER: Describe "The following git repositories should exist in C:/git"{ It "vm-ststua-checks" {...} # i.e. trimming down the title in the "It" block It "tdm-demos" {...} etc } Describe "The following repos should be up to date"{ It "vm-ststua-checks" {...} It "tdm-demos" {...} etc }
> 
> Or:
> 
> Describe "Verifying vm-status-checks repository"{ It "repo exists" {...} It "repo up to date" {...} } Describe "Verifying tdm-demos repository"{ It "repo exists" {...} It "repo up to date" {...} }
> 
> On balance, I prefer option 1, but what do you think?
> 
> Also, I bet it's possible to do something with for loops, so we can effectively just create a list of repo names at the top, and loop through them all, without needing to copy paste all over the place every time we either add a new repo, or a new test to run against all our repos, but we don't need to do that bit now.


Option 1 is nicer so I will go for that. I will also add the looping now as I don't think it will be too onerous.

**Comment by alex-yates-redgate** [comment]
Spectacular. Thank you Ryan!

**Comment by RyanSpr** [comment]
Loops are working - bit weird to loop through pester but it's working. Good to know for future tests :D

Ready to be approved

**Comment by alex-yates-redgate** [comment]
Excellent work mate. Works beautifully.

**Pull request merged**
